### ISSUE TITLE
macos-64 build failed

### ISSUE THREAD

**Issue by larsoner** [conda-forge/uv-feedstock#114]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1085501&view=logs&jobId=e0208569-136d-54da-4ec5-14d0e8771cbc&j=e0208569-136d-54da-4ec5-14d0e8771cbc&t=25992e30-3e2a-5788-2b3e-e373b0534bf7

@conda-forge/help-python would you be able to restart this CI so that the macos-64 build finishes and uploads? You can see it's missing here

https://anaconda.org/conda-forge/uv/files

And let me know if there is some other person/group I should ping next time or different procedure to follow to get the build to run again! (For example: could just bump the build number and merge, which would be a bit clunky but would work.)

**Comment by bollwyvl** [comment]
Kicked. Thanks for the report.

**Comment by larsoner** [comment]
All better, thanks!

![Image](https://github.com/user-attachments/assets/56515755-9066-4327-a4a6-f327ba805072)
